version: '3'

services:
 database:
    image: bitnami/postgresql
    ports: 
      - '5431:5432'
    container_name: garageImgDb
    restart: always
    volumes: 
      - carsDB-disk:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: garageDB
volumes: 
  carsDB-disk: